### ISSUE TITLE
Multi-day events

### ISSUE THREAD

**Issue by jimmythom** [marcusolsson/grafana-calendar-panel#1]
I was waiting for something like this for a long time. Are you planning to improve it? For me would be very useful possibility to show multiday events. Thanks and good luck...

**Comment by marcusolsson** [comment]
Thank you for the kind words! ❤️ 

I'm definitely up for improving the plugin. I've held off on new features until I've gotten some initial feedback on what would be useful. 

Some thoughts on multiday events:

- I think rather than multi-day, this really means support for events with a duration
- This would probably mean defining a dimension for both start and end time
- Start time would be required, but the end time dimension would be optional
- If a user has defined a dimension for end times, what would a null value mean? Is the event still ongoing?

**Comment by jimmythom** [comment]
It could be exactly how you wrote. Maybe the dimension for the end could be the same like the start dimension in case that it is event without duration. And if it is zero, its disabled event. But of course its up to you.
Another proposal to improve - if timestamp is only date (2021-03-04 00:00:00), mark it as wholeday event, if there is a different time, show it...

**Comment by andryyy** [comment]
Came to say the same: thank you!

For your thoughts and ideas: We can test whatever you implement. Sometimes it's easiest to just try and check what feels "good" and what feels "wrong". :)

**Comment by marcusolsson** [comment]
Thank you both! ❤️ 

Just wanted to let you know that I'm (slowly) working on this. It's mostly done. Can hopefully push this once I've solved overlapping intervals.

<img width="283" alt="Screenshot 2021-03-15 at 14 41 19@2x" src="https://user-images.githubusercontent.com/8396880/111162583-91a78780-859c-11eb-82a1-3be85e88cb74.png">

**Comment by riaz85in** [comment]
Hi, I am a newbie to grafana. I downloaded the calendar plugin but after adding the panel to dashboard, the dimension field time and text are disabled. Also, on top of the panel it shows this error msg "Cannot read property 'fields' of undefined". Plz help.

**Comment by riaz85in** [comment]
![16165083603116804081926025830807](https://user-images.githubusercontent.com/81244624/112159316-ff4e5600-8c23-11eb-9679-3353539e340d.jpg)

**Comment by riaz85in** [comment]
![16165084058068117042241697820989](https://user-images.githubusercontent.com/81244624/112159405-168d4380-8c24-11eb-82dc-31fa31ba2458.jpg)

**Comment by marcusolsson** [comment]
@riaz85in It doesn't seem like your question is related to the feature request in the original post. If you have questions on how to use the plugin, please use the [Discussions](https://github.com/marcusolsson/grafana-calendar-panel/discussions). That being said, try changing **Format as** to Table.

**Comment by riaz85in** [comment]
Hi, sorry. I posted in discussions. Plz help.
