### ISSUE TITLE
Show more details

### ISSUE THREAD

**Issue by fmuell2** [marcusolsson/grafana-calendar-panel#10]
There should be the possiblity to click on a calender entry and get more information for this entry like place, attendees, description. The information could be saved in the used datasource but in another field(s)

**Comment by marcusolsson** [comment]
This is an interesting feature. I think the main challenge is how to configure this without adding too many new dimensions. I think I'd like to understand how people will use these features first. Could you share some more details on your use case?

**Comment by fmuell2** [comment]
We would like to add a upcoming IT changes calender in our grafana environment. Right now we store information about start date, end date, title and addition information in a mariadb. The additional information is stored in one field, so maybe there has only one dimension to be added.

The additional information includes:
- Change Responsibles (functional and technical coordinator)
- Description
- Affected Services
- Effects of the change
- Ticket system id

I think it would be sufficient if there will be a popup or mouseover when selecting a specific calender entry to show the additional information stored in the datasource field

**Comment by marcusolsson** [comment]
In my other plugins I have a "Labels" dimension where you can select multiple fields to display as generic badges. Here's an example:

<img width="851" alt="Screenshot 2021-05-18 at 09 48 40@2x" src="https://user-images.githubusercontent.com/8396880/118612654-48eb9500-b7be-11eb-934c-8fc96334b9f8.png">

It's not very structured, but could be enough to display metadata in a generic way. 

Along with a Description dimension for longer texts, I think we could cover a lot of different use cases. WDYT?

**Comment by fmuell2** [comment]
For my specific case i would prefer the description dimension and structure the information as a long plain text. But i really think the labels would make sense too. E.g. when planning changes on different stages like prod/dev/test or the change is related to a specific third party vendor.

**Comment by marcusolsson** [comment]
Had a go at this. Would something like this work for you?

![description](https://user-images.githubusercontent.com/8396880/118666019-1dcf6880-b7f3-11eb-90b7-4ab04992ed3f.gif)

**Comment by fmuell2** [comment]
Looks really great! Does the longer description support linebreaks for better structuring?

**Comment by marcusolsson** [comment]
How would you like to define the line breaks? `\n`? Or maybe consider supporting Markdown in the description text?

**Comment by fmuell2** [comment]
Good question. I dont know what grafana exactly supports at this point out of the box. In my case i can manipulate the input field, so doesn´t really matter if just "\n" or "</ br>" or markdown.

**Comment by marcusolsson** [comment]
Available in v0.3.0 🚀 Please try it and and let me know how it can be improved!

**Comment by fmuell2** [comment]
Thank you very much for your fast support! I upgraded to 0.3 and testet it out. Unfortunatly it didn´t get the linebreaks work for me neither \n nor </br> was working for me. Or did i miss something?

**Comment by marcusolsson** [comment]
I decided to publish this without support for line breaks for now to gather more feedback. I created an issue for this here https://github.com/marcusolsson/grafana-calendar-panel/issues/11.
