### ISSUE TITLE
Show event name if event starts in day out of filter

### ISSUE THREAD

**Issue by jimmythom** [marcusolsson/grafana-calendar-panel#13]
In case of multiday event, If event starts in date, which is older than grafana filter, the name of event isnt shown. 
Also, in my opinion could be helpful to show the event name on start of each week (in case of multiweek events).

**Comment by marcusolsson** [comment]
Great feedback! Will be included in next release!

**Comment by jimmythom** [comment]
Super fast. Thanks...
