### ISSUE TITLE
Font settings in event name

### ISSUE THREAD

**Issue by jimmythom** [marcusolsson/grafana-calendar-panel#15]
Some possibility of font settings (size, bold, ...) in events name? Thanks

**Comment by marcusolsson** [comment]
I've been tweaking this back and forth 😆 I take it you'd like it to be bigger, more visible (at the expense of seeing less of the event text)? I'd prefer to find a setting that works for most rather than making it configurable.

**Comment by jimmythom** [comment]
Yes, in my case it is small. Isnt it possible to set size according to events count in a particular day - and maybe add possibility to set max events count showed in one day?

**Comment by marcusolsson** [comment]
I've published 0.4.1 with some improved legibility. Let me know what you think!

**Comment by jimmythom** [comment]
For me better, but it would depend on resolution and screen size. We will see what other users and use cases.
