### ISSUE TITLE
Show current day

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [marcusolsson/grafana-calendar-panel#18]
Hello,
So far in our test we saw that by default today overflows and spills under in the view and we need to scroll to see it. The image is what we get when we load the dashboard
![image](https://user-images.githubusercontent.com/34926125/119503805-a4dc8d80-bd6b-11eb-8003-5b9d99f2cbee.png)
How is it possible to have a different view of the calendar? It is fine to have the last month, but the current week should be visible without scrolling.

As you can see, in the panel I selected 30d in the "Relative time" option.

Thanks,
Mirko

**Comment by marcusolsson** [comment]
I agree that's annoying. How would you prefer to have it work? Would it be ok if the panel automatically scrolled to the bottom when the dashboard is loaded? Or would you want something like a Today button that takes you to the week of today?

**Comment by mirkocomparetti-synesis** [comment]
I think that the autoscroll is a good option. The "today" button option would not work in dashboard kiosk-like installations where there is no mouse interaction (which is our case).

Thanks @marcusolsson!

**Comment by marcusolsson** [comment]
Would this work for you?

![auto-scroll](https://user-images.githubusercontent.com/8396880/119876016-b4a0d100-bf27-11eb-99e7-91d7870a6354.gif)

**Comment by mirkocomparetti-synesis** [comment]
Looks great! Thanks a lot!
