### ISSUE TITLE
Add Data Links option

### ISSUE THREAD

**Issue by jeremyschulman** [marcusolsson/grafana-calendar-panel#25]
As a creator of calendar events I would like to have a mechanism to add a Grafana Data Link to the calendar event so that I can use this mechanism to open associated applications/URLs.  For example, let's say I have a calendar event that links to a Jira ticket (URL).  As a User of the Calendar I would like to be able click the Data Link to open the Jira ticket in my web brower.

**Comment by marcusolsson** [comment]
That's a excellent feature request 👍

**Comment by marcusolsson** [comment]
Available in v0.5.0.
