### ISSUE TITLE
Navigate to the first Data link when clicking on the event and no description provided

### ISSUE THREAD

**Issue by mikhailredis** [marcusolsson/grafana-calendar-panel#32]
I am using the Calendar plugin to display images stored in the databases and instead of opening a side panel with a data link inside, it will be great to just navigate to it.

Here is the screenshot:
![Screen Shot 2022-01-26 at 2 33 31 PM](https://user-images.githubusercontent.com/47795110/151233696-07e85da8-b1b0-4221-b53b-0a701e45ba59.png)

**Comment by marcusolsson** [comment]
Data link support would be a good addition. The sidebar works best when you're navigating events with description and tags. Maybe we can let the user configure the click action?

**Comment by mikhailredis** [comment]
What do you mean? `Datalink support would be a good addition` They are working already and displaying in the sidebar.

Click action is a good alternative. When can you add it?

**Comment by marcusolsson** [comment]
Sorry, mixing up plugins here 😓

Should be a relatively easy fix. I have some time today to look at it.
