### ISSUE TITLE
Text and time fields disabled in Grafana 7.4.3

### ISSUE THREAD

**Issue by riaz85in** [marcusolsson/grafana-calendar-panel#4]
Hi, I am a newbie to grafana. I downloaded the calendar plugin but after adding the panel to dashboard, the dimension fields - time and text are disabled. Also, on top of the panel it shows this error msg "Cannot read property 'fields' of undefined". Plz help.

**Comment by marcusolsson** [comment]
Closing in favor of https://github.com/marcusolsson/grafana-calendar-panel/discussions/3
